# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: berryboot2018
      # Runs a single command using the runners shell
      - name: Prepare
        run: |
          sudo apt update
          sudo apt install -y sed make binutils gcc g++ patch gzip bzip2 perl tar cpio unzip rsync file bc wget gcc-aarch64-linux-gnu lzop
      # Runs a set of commands using the runners shell
      - name: Build
        run: ./build-berryboot.sh device_pi64
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
                sudo tar -zcf output .
                gh release upload v1.0 output
